### ISSUE TITLE
How to get bounding box for sessions?

### ISSUE THREAD

**Issue by kristw** [tangtan/iStoryline.js#5]
I am curious what would be the best way to draw rectangle for each session. 
Is there a function for getting bounding box of sessions?

**Comment by tangtan** [comment]
We don't have such a function yet. But it's not difficult to obtain the rectangle of the session because we already know the paths of all characters and their sessions. You can check the *paths* and *_session* attrs of the `graph` object. 
From [the diagram](https://github.com/tangtan/istoryline/wiki/API-Reference), you can see there are some methods for operating sessions. We will release those methods plus what you mentioned here, export the shapes of sessions (e.g., rectangle or bubbles) after finishing the layout APIs.
